name: Add Required Reviewers

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add-reviewers:
    name: Add Reviewers
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate GitHub App token
        id: github-app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Get base sha
        id: get_base_sha
        run: |
          base_sha=${{ github.event.pull_request.base.sha }}
          echo "base_sha: $base_sha"
          echo "::set-output name=base_sha::$base_sha"
      
      - name: Execute script to add reviewers on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.github-app-token.outputs.token }}
          script: |
            // get the list of changed files path for the latest pus
            function extractReviewers(changed_files_paths) {
              const fs = require('fs')
              const required_approver_teams = new Set();
              for (const file_path of changed_files_paths) {
              let temp_file_path = file_path;
              do {
                // remove last word from the path
                const last_index = temp_file_path.lastIndexOf("/");
                temp_file_path = temp_file_path.substring(0, last_index);
                console.log(`temp_file_path: `,temp_file_path);

                // open the CODEOWNERS file (if exists)
                const owners_file_path = temp_file_path + ((temp_file_path.length > 0) ? "/" : "") + "CODEOWNERS";
                console.log(`owners_file_path: `,owners_file_path);
                const owners_file_exists = fs.existsSync(owners_file_path);
                console.log(`owners_file_exists: `,owners_file_exists);
                if (owners_file_exists) {
                  const lines = fs.readFileSync(owners_file_path, 'utf-8').split('\n').filter(line => line.startsWith('@'));
                  console.log(`lines: `,lines);

                  for (const line of lines) {
                    const approver_teams = line.trim().split(' ').filter(str => str !== '').map(word => word.substring(1));
                    for (const approver_team of approver_teams) {
                      required_approver_teams.add(approver_team);
                    }
                  }
                }
              } while(temp_file_path.length > 0);
              }
              console.log(`required_approver_teams: `,required_approver_teams);
              return required_approver_teams;
            }

            function getIntersection(set1, set2) { 
              const ans = new Set(); 
              for (let i of set2) { 
                  if (set1.has(i)) { 
                      ans.add(i); 
                  } 
              } 
              return ans; 
            }

            
            console.log(`action: `,context.payload.action);
            const before = context.payload.before;
            const after = context.payload.after;
            console.log(`before: `,before);
            console.log(`after: `,after);
            const { execSync } = require('child_process');
            let result = new Set()
            if(context.payload.action == 'opened') {
              const changed_file_names_in_last_push = execSync(`git diff --name-only HEAD HEAD~1`).toString()
              const changed_file_paths_in_last_push = changed_file_names_in_last_push.split('\n').filter(Boolean)
              result = extractReviewers(changed_file_paths_in_last_push)
            } else {
              const changed_file_names_in_current_push = execSync(`git diff --name-only ${context.payload.before} ${context.payload.after}`).toString()
             const changed_file_paths_in_current_push = changed_file_names_in_current_push.split('\n').filter(Boolean);
             let changed_files_in_entire_pr = ''
             let changed_files_before_last_push = ''
             changed_files_in_entire_pr = execSync(`git diff --name-only ${{ steps.get_base_sha.outputs.base_sha }} ${context.payload.after}`).toString()
             changed_files_before_last_push = execSync(`git diff --name-only ${{ steps.get_base_sha.outputs.base_sha }} ${context.payload.before}`).toString()

            let all_changed_files = changed_files_in_entire_pr.split('\n').filter(Boolean)
            let changed_file_paths_before_last_push = changed_files_before_last_push.split('\n').filter(Boolean)
            console.log(`changed_file_paths_in_current_push: `,changed_file_paths_in_current_push);
            console.log(`all_changed_files: `,all_changed_files);
            console.log(`changed_files_before_last_push: `,changed_files_before_last_push);
            const reviewers_for_changed_files_in_current_push = extractReviewers(changed_file_paths_in_current_push)
            const intersection = getIntersection(extractReviewers(changed_file_paths_before_last_push), reviewers_for_changed_files_in_current_push)
            if(intersection.size > 0) {
              result = getIntersection(extractReviewers(all_changed_files), reviewers_for_changed_files_in_current_push)
            }
            else {
              result = reviewers_for_changed_files_in_current_push
            }
            }
            console.log(`result: `,result)
            console.log(`size: `,result.size)
            if (result.size != 0) {
              github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                team_reviewers: Array.from(result)
              });
            }
