name: Check Required Reviewers Approvals

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Execute script
        uses: actions/github-script@v7
        with:
          script: |
            const query = `query($owner:String!, $name:String!, $pr_number: Int!) {
              repository(owner:$owner, name:$name){
                pullRequest(number: $pr_number) {
                reviews(first: 100, states: APPROVED) {
                  nodes {
                    author {
                      avatarUrl
                      login
                      resourcePath
                      url
                    }
                    onBehalfOf {
                    
                    }
                    
                  }
                }
              }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              pr_number: context.payload.pull_request.number
            }
            const result = await github.graphql(query, variables)
            console.log(result)
