name: testing

on:
  push:
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            core.setFailed("Fail the job")
