name: testing

on:
  workflow_dispatch:

jobs:

  use_nodemailer:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Nodemailer
        run: npm install nodemailer

      - name: Install xoauth2
        run: npm install xoauth2

      - name: Send email
        uses: actions/github-script@v7
        with:
          script: |
            const nodemailer = require("nodemailer")
            var xoauth2 = require('xoauth2');
            const username = "phan29tom@gmail.com"
            const password = "Vnd@8308782546"
            const transport = nodemailer.createTransport({
            host: "smtp.gmail.com",
            auth: {
              xoauth2: xoauth2.createXOAuth2Generator({
                user: username,
                pass: password
              })
            },
            secure: true,
            tls: {
              rejectUnauthorized: false
            }
            })

            const info = await transport.sendMail({
            from: username,
            to: "vedantnd2911@gmail.com",
            subject: "subject",
            text: "hello world"
            })
            console.log(`info: `,info)
          
