name: testing

on:
  workflow_dispatch:

jobs:

  use_nodemailer:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Send email
        uses: actions/github-script@v7
        with:
          script: |
            const nodemailer = require("nodemailer")
            const username = "phan29tom@gmail.com"
            const password = "Vnd@8308782546"
            const transport = nodemailer.createTransport({
            host: "gmail",
            auth: {
              user: username,
              pass: password
            },
            secure: true,
            tls: {
              rejectUnauthorized: false
            }
            })

            const info = await transport.sendMail({
            from: username,
            to: "vedantnd2911@gmail.com",
            subject: "subject",
            text: "hello world"
            })
            console.log(`info: `,info)
          
