name: testing

on:
  workflow_dispatch:

jobs:
  if_merged:
    runs-on: ubuntu-latest

    steps:
      - name: Get list of subscribers
        uses: actions/github-script@v7
        with:
          script: |
            const subscribers = await github.rest.activity.listWatchersForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo
            })
            console.log(`subscribers: `, subscribers)
