name: testing

on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          python3 ./.github/scripts/send_email.py
